interface Specialty {
    label: string;
  }
  
  const top100MedicalSpecialties: Specialty[] = [
    { label: 'Alergologia' },
    { label: 'Anestesiologia' },
    { label: 'Angiologia' },
    { label: 'Cardiologia' },
    { label: 'Cirurgia Cardiovascular' },
    { label: 'Cirurgia de Cabeça e Pescoço' },
    { label: 'Cirurgia do Aparelho Digestivo' },
    { label: 'Cirurgia Geral' },
    { label: 'Cirurgia Oncológica' },
    { label: 'Cirurgia Pediátrica' },
    { label: 'Cirurgia Plástica' },
    { label: 'Cirurgia Torácica' },
    { label: 'Cirurgia Vascular' },
    { label: 'Clínica Médica' },
    { label: 'Dermatologia' },
    { label: 'Endocrinologia e Metabologia' },
    { label: 'Gastroenterologia' },
    { label: 'Geriatria' },
    { label: 'Ginecologia e Obstetrícia' },
    { label: 'Hematologia e Hemoterapia' },
    { label: 'Hepatologia' },
    { label: 'Infectologia' },
    { label: 'Mastologia' },
    { label: 'Medicina de Família e Comunidade' },
    { label: 'Medicina do Trabalho' },
    { label: 'Medicina do Tráfego' },
    { label: 'Medicina Esportiva' },
    { label: 'Medicina Física e Reabilitação' },
    { label: 'Medicina Intensiva' },
    { label: 'Medicina Legal e Perícia Médica' },
    { label: 'Medicina Nuclear' },
    { label: 'Medicina Preventiva e Social' },
    { label: 'Nefrologia' },
    { label: 'Neurocirurgia' },
    { label: 'Neurologia' },
    { label: 'Nutrologia' },
    { label: 'Oftalmologia' },
    { label: 'Oncologia Clínica' },
    { label: 'Ortopedia e Traumatologia' },
    { label: 'Otorrinolaringologia' },
    { label: 'Patologia' },
    { label: 'Patologia Clínica/Medicina Laboratorial' },
    { label: 'Pediatria' },
    { label: 'Pneumologia' },
    { label: 'Psiquiatria' },
    { label: 'Radiologia e Diagnóstico por Imagem' },
    { label: 'Radioterapia' },
    { label: 'Reumatologia' },
    { label: 'Urologia' },
  ];
  
  export default top100MedicalSpecialties;
  